name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: scan-packages
      # run: dotnet restore "./dotnet/DotNet.Docker.csproj" --logger:"GitHubActions;report-warnings=true"
        run: |
          cd $(Build.SourcesDirectory)/dotnet/
          dotnet "./dotnet/DotNet.Docker.csproj" list package --vulnerable

        
    # - name: Build and push
    #   uses: docker/build-push-action@v6.0.0
    #   with:
    #     push: false
    #     tags: user/app:latest
